### ISSUE TITLE
CHIP Pro Eagle footprint has TWI1-SCK and TWI1-SDA swapped.

### ISSUE THREAD

**Issue by Groguard** [NextThingCo/Dev_Kit-Hardware#1]
The eagle footprint has the i2c lines swapped on TWI1-SCK and TWI1-SDA.

**Comment by blinkengus** [comment]
😬 good catch, will update!

**Comment by blinkengus** [comment]
library updated, and devkit source file PB15 + PB16 nets renamed correctly.
