### ISSUE TITLE
UART LEDs reversed or confusing

### ISSUE THREAD

**Issue by cinderblock** [NextThingCo/Dev_Kit-Hardware#2]
When I send serial data from my computer to the CHIP Pro via the FTDI USB-UART converter on the Pro Dev Kit, I expect the light next to the `RX1` pin on the CHIP Pro (labeled `RX` on Dev Kit) to flash. As it stands, the `TX` led flashes.

This would be fine if the `TX` and `RX` leds were closer to the USB-UART converter IC on the Dev Kit. However, as the LEDs are close to the pins on the CHIP Pro, it looks like they're intended to indicate activity on the pins that they are next to, similar to the LEDs attached to the SDIO pins.

I would like to see, at a minimum, the led positions swapped. A better solution might also include more obvious silk screens that indicate which device the `TX` and `RX` are with respect to.

**Comment by blinkengus** [comment]
I agree, having the UART bridge TX/RX indicators next to Pro reads funny. The good news is that CBUS2 & 3 can actually be software set to indicate either TX or RX activity from the FT230X USB-UART bridge. http://www.ftdichip.com/Support/Documents/DataSheets/ICs/DS_FT230X.pdf

Will flag for update on future revisions.

**Comment by cinderblock** [comment]
Great idea to just swap the LEDs in software!

To those that want to do this, here are Windows instructions:
1. Download FT_Prog from FTDI: http://www.ftdichip.com/Support/Utilities.htm#FT_PROG
1. Launch FT_Prog
1. Make sure other software is not using the FTDI com port
1. Hit "F5" key. Or, under `DEVICES`, `Scan and Parse`
1. Your FTDI device should show up in the list
1. Under your device, expand and find `FT EEPROM` > `Hardware Specific` > `CBUS Signals`
1. Swap the values for `C1` and `C2` in the dropdown menus
    - `C1` becomes `TXLED`
    - `C2` becomes `RXLED`
1. Program the device with `CTRL+P`. Or, under `DEVICES`, `Program`
1. Power cycle the FTDI
